version: '3.7'
services:
    mirakurun:
        build: mirakurun
        privileged: true
        volumes:
            - ./mirakurun/conf:/usr/local/etc/mirakurun
            - ./mirakurun/db:/usr/local/var/db/mirakurun
        devices:
            - /dev/pt3video0:/dev/pt3video0
            - /dev/pt3video1:/dev/pt3video1
            - /dev/pt3video2:/dev/pt3video2
            - /dev/pt3video3:/dev/pt3video3
            - /dev/bus/usb/001/009
        restart: always

    mysql:
        image: mariadb
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_DATABASE: epgstation
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: always

    epgstation:
        build: epgstation
        volumes:
            - ./epgstation/config:/usr/local/EPGStation/config
            - ./epgstation/data:/usr/local/EPGStation/data
            - ./epgstation/thumbnail:/usr/local/EPGStation/thumbnail
            - ./epgstation/logs:/usr/local/EPGStation/logs
            - ./recorded:/usr/local/EPGStation/recorded
        ports:
            - "8888:8888"
            - "8889:8889"
        restart: always

