version: '3.7'
services:
    mirakurun:
        build: mirakurun
        privileged: true
        labels:
            - "traefik.enable=false"
        volumes:
            - ./mirakurun/conf:/usr/local/etc/mirakurun
            - ./mirakurun/db:/usr/local/var/db/mirakurun
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/pt3video0:/dev/pt3video0
            - /dev/pt3video1:/dev/pt3video1
            - /dev/pt3video2:/dev/pt3video2
            - /dev/pt3video3:/dev/pt3video3
            - /dev/bus/usb/001/004
        restart: always

    mysql:
        image: mariadb
        labels:
            - "traefik.enable=false"
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_RANDOM_ROOT_PASSWORD: root
            MYSQL_DATABASE: epgstation
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: always

    tv:
        build: epgstation
        labels:
            - "traefik.http.routers.tv-epg.middlewares=auth"
            - "traefik.http.middlewares.auth.basicauth.users=yui:$$apr1$$2kJcSFij$$VY2/mxxbcWHxrEyet2VI90"
        networks:
            - desktop_default
            - default
        volumes:
            - ./epgstation/config:/usr/local/EPGStation/config
            - ./epgstation/data:/usr/local/EPGStation/data
            - ./epgstation/thumbnail:/usr/local/EPGStation/thumbnail
            - ./epgstation/logs:/usr/local/EPGStation/logs
            - ./recorded:/usr/local/EPGStation/recorded
        restart: always

networks:
    desktop_default:
        external: true
        name: desktop_default
