version: '3.7'
services:
    mirakurun:
        image: chinachu/mirakurun
        cap_add:
            - SYS_ADMIN
            - SYS_NICE
        volumes:
            - ./mirakurun/conf:/app-config
            - ./mirakurun/data:/app-data
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/bus:/dev/bus
            - /dev/dvb:/dev/dvb
        restart: always
    epg-db:
        image: mariadb
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_RANDOM_ROOT_PASSWORD: root
            MYSQL_DATABASE: epgstation
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: always
    tv:
        build: epgstation
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.tv-epg.middlewares=auth"
            - "traefik.http.middlewares.auth.basicauth.users=yui:$$apr1$$2kJcSFij$$VY2/mxxbcWHxrEyet2VI90"
        networks:
            - compose_default
            - default
        volumes:
            - ./epgstation/config:/app/config
            - ./epgstation/data:/app/data
            - ./epgstation/thumbnail:/app/thumbnail
            - ./epgstation/logs:/app/logs
            - ./recorded:/app/recorded
        restart: always

networks:
    compose_default:
        external: true
        name: compose_default
