version: '3.8'
services:
    mirakurun:
        image: chinachu/mirakurun
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mirakurun.middlewares=auth"
            - "traefik.http.services.mirakurun.loadbalancer.server.port=40772"
            - "traefik.http.routers.mirakurun.rule=Host(`m.c.daco.dev`)"
        networks:
            - compose_default
            - default
        cap_add:
            - SYS_ADMIN
            - SYS_NICE
        volumes:
            - ./mirakurun/conf:/app-config
            - ./mirakurun/data:/app-data
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/bus:/dev/bus
            - /dev/dvb:/dev/dvb
        restart: always
    db:
        image: mariadb
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: epgstation
            MYSQL_DATABASE: epgstation
            TZ: "Asia/Tokyo"
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: always
    tv:
        build:
            context: "./epgstation"
            dockerfile: "alpine.Dockerfile"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.tv.middlewares=auth"
            - "traefik.http.middlewares.auth.basicauth.users={set htpasswd here}"
        networks:
            - compose_default
            - default
        volumes:
            - ./epgstation/config:/app/config
            - ./epgstation/data:/app/data
            - ./epgstation/thumbnail:/app/thumbnail
            - ./epgstation/logs:/app/logs
            - ./recorded:/app/recorded
        environment:
            TZ: "Asia/Tokyo"
        restart: always

networks:
    compose_default:
        external: true
        name: compose_default
