epg:
  cache-dir: /var/lib/mirakc/epg
server:
  addrs:
    - http: '0.0.0.0:40772'
  mounts:
    /miraview:
      path: /var/lib/miraview
      index: index.html
channels:
tuners:
  - name: adapter0
    types: [BS, CS]
    command: >-
      recdvb --dev 0 {{channel}} {{duration}} -
  - name: adapter1
    types: [GR]
    command: >-
      recdvb --dev 1 {{channel}} {{duration}} -
  - name: adapter2
    types: [BS, CS]
    command: >-
      recdvb --dev 2 {{channel}} {{duration}} -
  - name: adapter3
    types: [GR]
    command: >-
      recdvb --dev 3 {{channel}} {{duration}} -
filters:
  decode-filter:
    command: >-
      arib-b25-stream-test -v 0